title: Oracle Windows Instance
description: Windows Instance creation with storage attachment  
informationalText: "The Resource Manager Stack just creates the infrastructure components (compute)."
schemaVersion: 1.1.0
version: "20240415"
locale: "en"

variableGroups:
  - title: "Tags"
    visible: true
    variables:
      - freeform_tags

variables:
  # Hidden variables
  tenancy_ocid:
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    type: string
    required: true
    visible: false

  region:
    title: Region
    description: The region in which to create all resources
    type: oci:identity:region:name
    required: true
    visible: false

  user_ocid:
    title: User ID
    description: The Oracle Cloud Identifier (OCID) for the user
    type: string
    visible: false

  fingerprint:
    title: Private Key Fingerprint
    type: string
    visible: false

  block_storage_policy:
    title: Block Storage Policy for Block and Boot Volumes
    description: Select the type of policy backup for boot volume.
    type: oci:blockstorage:policies:id
    required: true
    default: bronze
    visible: true

  vcn_cidr:
    title: Virtual Cloud Network CIDR
    visible: true
    type: enum
    enum:
      - 172.16.0.0/16
      - 11.0.0.0/16
      - 192.168.0.0/16
    default: 11.0.0.0/16
    required: true

  vcn_dns_label:
    title: Virtual Cloud Network DNS Label
    type: string
    required: true
    default: winvcn
    visible: true

  compartment_ocid:
    title: Target Compartment
    description: The target compartment to provision application compute instances.
    type: oci:identity:compartment:id
    required: true
    visible: true

# Hidden variables
  compute_instance_user:
    title: Compute Instance user
    description: The deployment creates application and database instances in private subnets. To access these instances, a bastion host is created using VMStandard2.1 shape. Bastion host VM can be deleted if infrastructure needs to accessed from on-premise using VPN/Fastconnect
    type: string
    default: opc
    visible: false

  InstanceOS:
    title: Instance os
    description: Operating system instance host
    type: string
    visible: false

  timeout:
    type: string
    visible: false

  image_id:
    type: map
    visible: false

outputs:
  ApplicationPrivateIPs:
    title: "Instance Details"
    type: string
    visible: true